// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/HelloWorld.proto

#include "protos/HelloWorld.pb.h"
#include "protos/HelloWorld.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* HelloWorld_method_names[] = {
  "/HelloWorld/echo",
};

std::unique_ptr< HelloWorld::Stub> HelloWorld::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HelloWorld::Stub> stub(new HelloWorld::Stub(channel, options));
  return stub;
}

HelloWorld::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_echo_(HelloWorld_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HelloWorld::Stub::echo(::grpc::ClientContext* context, const ::Message& request, ::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Message, ::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_echo_, context, request, response);
}

void HelloWorld::Stub::async::echo(::grpc::ClientContext* context, const ::Message* request, ::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Message, ::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_echo_, context, request, response, std::move(f));
}

void HelloWorld::Stub::async::echo(::grpc::ClientContext* context, const ::Message* request, ::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Message>* HelloWorld::Stub::PrepareAsyncechoRaw(::grpc::ClientContext* context, const ::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Message, ::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Message>* HelloWorld::Stub::AsyncechoRaw(::grpc::ClientContext* context, const ::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncechoRaw(context, request, cq);
  result->StartCall();
  return result;
}

HelloWorld::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloWorld_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HelloWorld::Service, ::Message, ::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HelloWorld::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Message* req,
             ::Message* resp) {
               return service->echo(ctx, req, resp);
             }, this)));
}

HelloWorld::Service::~Service() {
}

::grpc::Status HelloWorld::Service::echo(::grpc::ServerContext* context, const ::Message* request, ::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


